### ISSUE TITLE
やはり共有できません。

### ISSUE THREAD

**Issue by s1f102402248** [s1F102401225/team-project4#3]
なのでスライドが完成したらそのファイルを送って頂きたいです。よろしくお願いします。

**Comment by s1F102401225** [comment]
対応遅れてごめん！
[team-project4.pptx](https://github.com/user-attachments/files/15861056/team-project4.pptx)
上のリンクを踏んでもらうとダウンロードできると思う！

**Comment by s1f102402248** [comment]
ありがとう！
