### ISSUE TITLE
index.htmlの作成

### ISSUE THREAD

**Issue by s1F102401225** [s1F102401225/team-project4#4]
骨組みは作ったから、こうしたほうがいいなどの意見あったら遠慮なく書いてください。

**Comment by s1f102402248** [comment]
それぞれのゲームの画像いれるのはどう？その画像は各々が選んでくる形で

**Comment by s1F102401225** [comment]
いいね、そうしたら選んだ画像はImgフォルダの中に入れておいてほしい！
